# Generated by Django 4.1 on 2022-08-19 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emastersystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
    ]
