# Generated by Django 4.1 on 2022-08-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emastersystem', '0003_employee_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='experience',
            new_name='yearofexperience',
        ),
        migrations.AddField(
            model_name='employee',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
