# Generated by Django 4.1 on 2022-08-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emastersystem', '0005_employee_companyname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='companyname',
            new_name='company',
        ),
    ]
