# Generated by Django 4.1 on 2022-08-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emastersystem', '0006_rename_companyname_employee_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
